//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_Timesheet
    {
        public int Timesheet_ID { get; set; }
        public int Emp_ID { get; set; }
        public System.DateTime WeekStartingDate { get; set; }
        public decimal HoursWorked { get; set; }
        public string Status { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
