//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Emp_Timesheet = new HashSet<Emp_Timesheet>();
        }
    
        public int Emp_ID { get; set; }
        public string Emp_First_Name { get; set; }
        public string Emp_Last_Name { get; set; }
        public Nullable<System.DateTime> Emp_Date_of_Birth { get; set; }
        public Nullable<System.DateTime> Emp_Date_of_Joining { get; set; }
        public Nullable<int> Emp_Dept_ID { get; set; }
        public string Emp_Grade { get; set; }
        public string Emp_Designation { get; set; }
        public Nullable<decimal> Emp_Salary { get; set; }
        public string Emp_Gender { get; set; }
        public string Emp_Marital_Status { get; set; }
        public string Emp_Home_Address { get; set; }
        public string Emp_Contact_Num { get; set; }
        public string Status { get; set; }
    
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emp_Timesheet> Emp_Timesheet { get; set; }
        public virtual Grade_master Grade_master { get; set; }
    }
}
